name: cloudhub - build and deploy

on:
  push:
    branches:
      - 'master'
      - 'feature/cicd-deployment'
  pull_request:
    branches:
      - 'master'
      - 'feature/cicd-deployment'

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest
    env:
        PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
        PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        environment: 'Dev'
        name: 'cicd-deployment-dev'
        #SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
        #SANDBOX_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}
        
    steps:
    - name: checkout Repository
      uses: actions/checkout@v3
    - name: Cache Dependencies
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build and deploy with Maven
      run: mvn clean -B deploy -DmuleDeploy -s .maven/settings.xml

      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  #  - name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6