name: cloudhub - build and deploy

on:
  push:
    branches:
      - "master"
      - "test"
      - "dev"
      - "feature/cicd-deployment"
  pull_request:
    branches:
      - "master"
      - "test"
      - "dev"
      - "feature/cicd-deployment"

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      PLATFORM_USERNAME: '0591322cb898480a8b70a8ce7cdeff86'
      PLATFORM_PASSWORD: '9C4Ec344092D44D09112e2d36639C493'
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -s .maven/settings.xml

      - name: Upload Artifact
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - name: Deploy To Dev
        if: github.ref == 'refs/heads/feature/cicd-deployment'
        env:
          PLATFORM_USERNAME: '0591322cb898480a8b70a8ce7cdeff86'
          PLATFORM_PASSWORD: '9C4Ec344092D44D09112e2d36639C493'
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          environment: 'Dev'
          name: 'cicd-deployment-dev'
          target: "Cloudhub-US-East-2"
          replicas: "1"
          cores: "0.1"
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
          channel: "#github-action-poc-1"
          # message: Starting Deployment...
        if: always()
