Skip to content
API1187
/
CICD-gitLab

Type / to search

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
cloudhub - build and deploy
Update maven-publish.yml #53
Jobs
Run details
Workflow file for this run
.github/workflows/maven-publish.yml at d487d1c
name: cloudhub - build and deploy

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master' 

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: checkout Repository
      uses: actions/checkout@v2
    - name: Cache Dependencies
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package -s .maven/settings.xml

    - name: Upload Artifact
      run: mkdir staging && cp target/*.jar staging 
    - uses: actions/upload-artifact@v2
      with: 
        name: Package
        path: staging

    - name: Deploy with Maven
      run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml


      env:
        PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
        PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }} 
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        #SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
        #SANDBOX_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}
        
    - name: slack notification
      uses: act10ns/slack@v1
      with:
       status: ${{ job.status }}
       steps: ${{ toJson(steps) }}
       channel: '#github-action-poc'
       if: always()
   

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  #  - name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
Update maven-publish.yml · API1187/CICD-gitLab@d487d1c
